### PR TITLE
WIP: Added more joints wrappers and draft demo for it

### PR DESCRIPTION
**Pull request by andrey-zakharov**
Hello, thanx for great lib.
Just adding more PhysX joint wrappers, and need for advice how to implement D6Joint interface.

As in c++ its just set of functions `setMotion(PxD6Axis, PxD6Motion)`. What would be best:
make it as set of functions like `freeMotionX`, `lockMotionX`, `freeMotionY`, `lockMotionY`...
or make public available enum wrapping `PxD6Axis` and `PxD6Motion` values and make pair of `freeMotion(Axis)`, `lockMotion(Axis)`? or just reveal `Px*` enums as arguments ?

### CODE REVIEW

**Comment by fabmax** [comment]
Very nice!

I guess a separate function for each combination of axis and motion type would result in too many functions.

The other options are fine by me. Just to get a feeling how these would look like:
```kotlin
// option a: one function per motion type
d6Joint
    .setLocked(X_AXIS)
    .setLimited(Y_AXIS)
    .setFree(Z_AXIS)

// option b: one function per axis
d6Joint
    .setMotionX(LOCKED)
    .setMotionY(LIMITED)
    .setMotionZ(FREE)

// option c: C++ like interface
d6Joint
    .setMotion(X_AXIS, LOCKED)
    .setMotion(Y_AXIS, LIMITED)
    .setMotion(Z_AXIS, FREE)
```
When looking at it I think I prefer option b, I think it's the best readable.

**Review by Protoxy22 — APPROVED** [review]

**Comment by fabmax** [comment]
The D6 joint interface looks pretty good now. But the physics behavior in the demo seems to be a bit unstable. A few of the spheres jump around like crazy when I run it.

**Comment by andrey-zakharov** [comment]
> The D6 joint interface looks pretty good now. But the physics behavior in the demo seems to be a bit unstable. A few of the spheres jump around like crazy when I run it.

Thats what i'm trying to figure out. Some PhysX glitches/misconfigurations?

**Comment by fabmax** [comment]
Usually these glitches appear when the joint constraints cannot be fulfilled or if the initial object positions violate the constraints too much.

**Comment by fabmax** [comment]
Whoopsie, I accidentaly merged this into main...

Anyway, I think the extended joint classes are good to go, but I set the penbdulum demo to hidden for now

**Pull request merged**
